"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import warnings
from pathlib import Path

from dotenv import load_dotenv  # type: ignore

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR / ".env.local")
load_dotenv(BASE_DIR / ".env.development", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        # 开发环境允许使用默认值，但会警告
        SECRET_KEY = "django-insecure-dev-key-change-in-production"
        warnings.warn(
            "SECRET_KEY未设置，使用开发环境默认值。生产环境必须设置DJANGO_SECRET_KEY环境变量！",
            RuntimeWarning,
        )
    else:
        # 生产环境必须设置SECRET_KEY
        raise ValueError(
            "SECRET_KEY未设置！生产环境必须设置DJANGO_SECRET_KEY环境变量。"
            "请使用强随机生成的密钥（至少50字符）。"
        )

# SECURITY WARNING: don't run with debug turned on in production!
# 默认关闭DEBUG，生产环境必须明确设置DJANGO_DEBUG=false
_debug_env = os.getenv("DJANGO_DEBUG", "").lower()
if _debug_env == "true":
    DEBUG = True
elif _debug_env == "false":
    DEBUG = False
else:
    # 未设置时，根据环境判断：本地开发环境默认True，其他环境默认False
    _is_local = os.getenv("ENVIRONMENT", "").lower() in {"local", "development", "dev"}
    DEBUG = _is_local
    if not _is_local:
        warnings.warn(
            "DJANGO_DEBUG未设置，已默认关闭DEBUG模式。"
            "如需开启，请明确设置DJANGO_DEBUG=true（仅限开发环境）",
            RuntimeWarning,
        )

# 生产环境安全检查：如果DEBUG=True且不在本地环境，发出警告
if DEBUG and os.getenv("ENVIRONMENT", "").lower() not in {"local", "development", "dev", ""}:
    warnings.warn(
        "⚠️ 警告：生产环境检测到DEBUG=True！这可能导致敏感信息泄露。"
        "请确保这是开发/测试环境，或设置DJANGO_DEBUG=false",
        RuntimeWarning,
    )

_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(",") if host.strip()]

if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]

_loopback_hosts = {"127.0.0.1", "localhost"}
for _host in _loopback_hosts:
    if _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    "corsheaders",
    "rest_framework",
    "core",
]

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "config.middleware.TraceIdMiddleware",  # 请求追踪中间件，必须在最前面
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_engine = os.getenv("DB_ENGINE", "sqlite").strip().lower()
if _db_engine in {"postgres", "postgresql", "psql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": int(os.getenv("DB_PORT", "5432")),
            "NAME": os.getenv("DB_NAME", "echo"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
            "OPTIONS": {
                # 避免 DNS 反复解析
                "connect_timeout": int(os.getenv("DB_CONNECT_TIMEOUT", "5")),
            },
        }
    }
elif _db_engine in {"mysql", "mariadb"}:
    # 使用自定义后端以兼容 MySQL 5.7（生产环境建议升级到 MySQL 8.0+）
    _mysql_engine = os.getenv("MYSQL_USE_CUSTOM_BACKEND", "true").lower() == "true"
    if _mysql_engine:
        DATABASES = {
            "default": {
                "ENGINE": "core.db_backend",
                "HOST": os.getenv("DB_HOST", "127.0.0.1"),
                "PORT": int(os.getenv("DB_PORT", "3306")),
                "NAME": os.getenv("DB_NAME", "echo"),
                "USER": os.getenv("DB_USER", "root"),
                "PASSWORD": os.getenv("DB_PASSWORD", ""),
                "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
                "OPTIONS": {
                    "charset": "utf8mb4",
                    "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                    "connect_timeout": int(os.getenv("DB_CONNECT_TIMEOUT", "5")),
                },
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "HOST": os.getenv("DB_HOST", "127.0.0.1"),
                "PORT": int(os.getenv("DB_PORT", "3306")),
                "NAME": os.getenv("DB_NAME", "echo"),
                "USER": os.getenv("DB_USER", "root"),
                "PASSWORD": os.getenv("DB_PASSWORD", ""),
                "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
                "OPTIONS": {
                    "charset": "utf8mb4",
                    "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                    "connect_timeout": int(os.getenv("DB_CONNECT_TIMEOUT", "5")),
                },
            }
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Object storage (TOS) configuration
USE_TOS_STORAGE = os.getenv("DJANGO_USE_TOS_STORAGE", "false").lower() == "true"
TOS_ACCESS_KEY_ID = os.getenv("TOS_ACCESS_KEY_ID")
TOS_SECRET_ACCESS_KEY = os.getenv("TOS_SECRET_ACCESS_KEY")
TOS_REGION_NAME = os.getenv("TOS_REGION_NAME", "cn-beijing")
TOS_ENDPOINT_URL = os.getenv("TOS_ENDPOINT_URL")
TOS_BUCKET = os.getenv("TOS_BUCKET")
TOS_MEDIA_LOCATION = os.getenv("TOS_MEDIA_LOCATION", "uploads")
TOS_CUSTOM_DOMAIN = os.getenv("TOS_CUSTOM_DOMAIN", "")

_required_tos_settings = {
    "TOS_ACCESS_KEY_ID": TOS_ACCESS_KEY_ID,
    "TOS_SECRET_ACCESS_KEY": TOS_SECRET_ACCESS_KEY,
    "TOS_BUCKET": TOS_BUCKET,
    "TOS_ENDPOINT_URL": TOS_ENDPOINT_URL,
}

_tos_flag = os.getenv("DJANGO_USE_TOS_STORAGE")
if _tos_flag is None:
    USE_TOS_STORAGE = all(value not in {None, ""} for value in _required_tos_settings.values())
else:
    USE_TOS_STORAGE = _tos_flag.lower() == "true"

if USE_TOS_STORAGE and any(value in {None, ""} for value in _required_tos_settings.values()):
    missing_keys = [key for key, value in _required_tos_settings.items() if value in {None, ""}]
    warnings.warn(
        "TOS 存储配置不完整，已自动回退到本地媒体存储。缺失的配置项："
        + ", ".join(missing_keys),
        RuntimeWarning,
    )
    USE_TOS_STORAGE = False

# 图片 URL 代理配置：当 TOS 存储桶未配置 CORS 时，可通过此选项强制使用代理 URL
FORCE_IMAGE_PROXY_URL = os.getenv("DJANGO_FORCE_IMAGE_PROXY_URL", "false").lower() == "true"

if USE_TOS_STORAGE:
    DEFAULT_FILE_STORAGE = "config.storage.TOSMediaStorage"
    AWS_ACCESS_KEY_ID = TOS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = TOS_SECRET_ACCESS_KEY
    AWS_S3_REGION_NAME = TOS_REGION_NAME
    AWS_S3_ENDPOINT_URL = TOS_ENDPOINT_URL
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "virtual"

    STORAGES = {
        "default": {
            "BACKEND": "config.storage.TOSMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    _media_prefix = f"{TOS_MEDIA_LOCATION.strip('/')}/" if TOS_MEDIA_LOCATION else ""
    if _media_prefix == "/":
        _media_prefix = ""

    if TOS_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{TOS_CUSTOM_DOMAIN.rstrip('/')}/{_media_prefix}"
    elif TOS_BUCKET and TOS_ENDPOINT_URL:
        endpoint_host = TOS_ENDPOINT_URL.replace("https://", "").replace("http://", "").rstrip("/")
        MEDIA_URL = f"https://{TOS_BUCKET}.{endpoint_host}/{_media_prefix}"

_cors_origins = os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(",") if origin.strip()]

if not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ]

_cors_regex = os.getenv("DJANGO_CORS_ALLOWED_ORIGIN_REGEXES", "")
CORS_ALLOWED_ORIGIN_REGEXES = [regex.strip() for regex in _cors_regex.split(",") if regex.strip()]

if not CORS_ALLOWED_ORIGIN_REGEXES and DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^https?://localhost(?::\d+)?$",
        r"^https?://127\.0\.0\.1(?::\d+)?$",
        r"^https?://192\.168\.\d{1,3}\.\d{1,3}(?::\d+)?$",
        r"^https?://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(?::\d+)?$",
        r"^https?://172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}(?::\d+)?$",
    ]

CORS_ALLOW_CREDENTIALS = True

# CORS配置：生产环境必须明确配置允许的来源
_cors_allow_all = os.getenv("DJANGO_CORS_ALLOW_ALL", "")
if _cors_allow_all:
    CORS_ALLOW_ALL_ORIGINS = _cors_allow_all.lower() == "true"
elif DEBUG:
    # 仅在DEBUG模式下允许所有来源（开发环境）
    CORS_ALLOW_ALL_ORIGINS = True
    warnings.warn(
        "DEBUG模式下CORS允许所有来源。生产环境请设置DJANGO_CORS_ALLOWED_ORIGINS明确指定允许的来源。",
        RuntimeWarning,
    )
else:
    # 生产环境默认不允许所有来源
    CORS_ALLOW_ALL_ORIGINS = False
    if not CORS_ALLOWED_ORIGINS:
        warnings.warn(
            "生产环境未配置CORS允许的来源。请设置DJANGO_CORS_ALLOWED_ORIGINS环境变量。",
            RuntimeWarning,
        )

_csrf_trusted = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_trusted.split(",") if origin.strip()]

if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(
        [
            "http://localhost",
            "http://127.0.0.1",
        ]
    )

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.AuthTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "120/min",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "http://192.168.3.3:8000").rstrip("/")


# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("SMTP_HOST", "smtp.163.com")
EMAIL_PORT = int(os.getenv("SMTP_PORT", "465"))
_use_tls = os.getenv("SMTP_USE_TLS", "false").lower() == "true"
_use_ssl = os.getenv("SMTP_USE_SSL", "true").lower() == "true"

if _use_tls and _use_ssl:
    _use_ssl = False

EMAIL_USE_TLS = _use_tls
EMAIL_USE_SSL = _use_ssl
EMAIL_HOST_USER = os.getenv("SMTP_USERNAME", "echodraw@163.com")
EMAIL_HOST_PASSWORD = os.getenv("SMTP_PASSWORD")
if not EMAIL_HOST_PASSWORD:
    warnings.warn(
        "SMTP_PASSWORD未设置，邮件发送功能可能无法正常工作。",
        RuntimeWarning,
    )
DEFAULT_FROM_EMAIL = os.getenv("SMTP_FROM_EMAIL", EMAIL_HOST_USER)
EMAIL_TIMEOUT = int(os.getenv("SMTP_TIMEOUT", "10"))

# Celery / Redis (可选)
CELERY_ENABLED = os.getenv("CELERY_ENABLED", "false").lower() == "true"
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1")
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "false").lower() == "true"
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "60"))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "45"))

# File upload size limits (10MB)
# 限制文件上传大小，防止内存溢出
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} [{name}] {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "with_trace": {
            "format": "[{levelname}] {asctime} [{name}] [trace_id={trace_id}] {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "filters": {
        "require_trace_id": {
            "()": "config.logging_filters.RequireTraceIdFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "with_trace",
            "filters": ["require_trace_id"],
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(BASE_DIR / "logs" / "django.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "with_trace",
            "filters": ["require_trace_id"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "core": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

# 确保日志目录存在
_logs_dir = BASE_DIR / "logs"
if not _logs_dir.exists():
    _logs_dir.mkdir(exist_ok=True)