# Generated by Django 5.2.7 on 2025-11-08 01:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyHistoryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "headline",
                    models.CharField(
                        blank=True, help_text="可选标题，例如节日名称。", max_length=128
                    ),
                ),
                ("text", models.TextField(help_text="“历史上的今天”文案内容。")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EncouragementMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="鼓励类文案，将随机展示。")),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1, help_text="权重越高，被选中的概率越大。"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadConditionalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="条件文案名称，便于后台识别。", max_length=128
                    ),
                ),
                ("text", models.TextField(help_text="满足条件时展示的文案内容。")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="数字越小优先级越高。"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applies_when_no_upload",
                    models.BooleanField(
                        default=False,
                        help_text="勾选后，若用户暂无上传记录也会匹配此文案。",
                    ),
                ),
                (
                    "min_days_since_last_upload",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="距离上次上传的最少天数（含）。",
                        null=True,
                    ),
                ),
                (
                    "max_days_since_last_upload",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="距离上次上传的最多天数（含）。",
                        null=True,
                    ),
                ),
                (
                    "min_self_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="上一次自评分最低值（含）。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_self_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="上一次自评分最高值（含）。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "match_moods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="限定心情标签（任意匹配一个即满足）。",
                    ),
                ),
                (
                    "match_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="限定作品标签（任意匹配一个即满足）。",
                    ),
                ),
                (
                    "min_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="创作时长最低值（含，单位：分钟）。",
                        null=True,
                    ),
                ),
                (
                    "max_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="创作时长最高值（含，单位：分钟）。",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "self_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="创作者自评分，范围 0-100。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "mood_label",
                    models.CharField(
                        blank=True, help_text="上传时选择的心情标签。", max_length=64
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="上传时选择的作品标签列表。"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="此次创作的时长（分钟）。", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-uploaded_at"],
                        name="core_userup_user_id_a06025_idx",
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="core_userup_uploade_c27852_idx"
                    ),
                ],
            },
        ),
    ]
