# Generated by Django 5.2.7 on 2025-11-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dailyhistorymessage_encouragementmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("reset_password", "Reset Password"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="用于追踪打卡来源，例如 'app'、'admin'。",
                        max_length=32,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="core_dailyc_user_id_272e4a_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_daily_checkin_per_user"
                    )
                ],
            },
        ),
    ]
