# Generated by Django 5.2.7 on 2025-11-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_emailverification_purpose_dailycheckin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="唯一标识符，建议使用英文短标签。",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="成就名称。", max_length=128)),
                (
                    "description",
                    models.TextField(blank=True, help_text="成就描述文案。"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="可选分类标签，便于分组展示。",
                        max_length=64,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="成就图标（URL 或资源标识）。",
                        max_length=256,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="用于排序，数值越小越靠前。"
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True, default=dict, help_text="成就判定条件的 JSON 描述。"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="附加元数据，例如奖励值等。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="TestAccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="后台展示用昵称，默认为邮箱前缀。",
                        max_length=128,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="测试账号备注，例如用途、测试场景等。"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="自定义标签列表，便于分类筛选。",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="附加元数据，例如模拟配置。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__email"],
            },
        ),
    ]
