# Generated by Django 5.2.7 on 2025-11-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userupload_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="title",
            field=models.CharField(
                blank=True, help_text="作品标题，用于前端展示。", max_length=120
            ),
        ),
    ]
