# Generated by Django 5.2.7 on 2025-11-09 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userupload_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortTermGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        help_text="挑战持续天数，范围 1-90 天。",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("same", "Same Task Daily"),
                            ("different", "Different Task Daily"),
                        ],
                        default="different",
                        help_text="任务结构类型：每日相同或每日不同。",
                        max_length=16,
                    ),
                ),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="任务安排列表，元素包含 day_index 与任务条目。",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_term_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_shortt_user_id_c6191f_idx",
                    ),
                    models.Index(
                        fields=["user", "plan_type"],
                        name="core_shortt_user_id_e9b8fe_idx",
                    ),
                ],
            },
        ),
    ]
