# Generated by Django 5.2.7 on 2025-11-09 16:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_shorttermgoal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LongTermGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="长期计划标题。", max_length=160),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="长期计划描述，展示在详情页顶部。",
                    ),
                ),
                (
                    "target_hours",
                    models.PositiveIntegerField(
                        help_text="目标投入总小时数。",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "checkpoint_count",
                    models.PositiveSmallIntegerField(
                        help_text="检查点数量，用于划分阶段。",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="计划开始时间，用于统计进度。",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_term_goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["target_hours"],
                        name="core_lt_goal_target_hours_idx",
                    )
                ],
            },
        ),
    ]


