# Generated by Django 5.2.7 on 2025-11-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_longtermgoal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortTermTaskPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="用于构建短期任务计划的唯一任务标识。",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="任务分类，便于前端分组展示。", max_length=64
                    ),
                ),
                ("title", models.CharField(help_text="任务名称。", max_length=160)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="任务简介，将展示给用户。", max_length=240
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关闭后将从用户端隐藏该任务预设。"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="排序权重，数值越小越靠前。"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="附加元数据，保留扩展字段。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["category", "display_order"],
                        name="core_shortt_categor_51030b_idx",
                    ),
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="core_shortt_is_acti_f49d0d_idx",
                    ),
                ],
            },
        ),
    ]
