# Generated by Django 5.2.7 on 2025-11-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_split_achievements_into_groups"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="achievement",
            new_name="core_achiev_group_i_4b8ebe_idx",
            old_name="core_achiev_group_le_idx",
        ),
        migrations.RenameIndex(
            model_name="usertaskpreset",
            new_name="core_userta_user_id_8e1699_idx",
            old_name="core_usert_user_id_a5e152_idx",
        ),
        migrations.RenameIndex(
            model_name="usertaskpreset",
            new_name="core_userta_user_id_a30a0f_idx",
            old_name="core_usert_user_id_8036e5_idx",
        ),
    ]
