# Generated by Django 5.2.7 on 2025-11-14 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_enforce_unique_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="条件文案名称，便于后台识别。", max_length=128
                    ),
                ),
                ("text", models.TextField(help_text="满足条件时展示的文案内容。")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="数字越小优先级越高，当多个条件同时满足时，优先显示优先级高的。",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_total_checkins",
                    models.PositiveIntegerField(
                        blank=True, help_text="总打卡次数最低值（含）。", null=True
                    ),
                ),
                (
                    "max_total_checkins",
                    models.PositiveIntegerField(
                        blank=True, help_text="总打卡次数最高值（含）。", null=True
                    ),
                ),
                (
                    "min_streak_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="连续打卡天数最低值（含）。", null=True
                    ),
                ),
                (
                    "max_streak_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="连续打卡天数最高值（含）。", null=True
                    ),
                ),
                (
                    "min_total_uploads",
                    models.PositiveIntegerField(
                        blank=True, help_text="总上传次数最低值（含）。", null=True
                    ),
                ),
                (
                    "max_total_uploads",
                    models.PositiveIntegerField(
                        blank=True, help_text="总上传次数最高值（含）。", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "条件文案",
                "verbose_name_plural": "条件文案",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="HolidayMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        help_text="月份（1-12）。",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        help_text="日期（1-31）。",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, help_text="可选标题，例如节日名称。", max_length=128
                    ),
                ),
                ("text", models.TextField(help_text="节日文案内容。")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "节日文案",
                "verbose_name_plural": "节日文案",
                "ordering": ["month", "day"],
            },
        ),
    ]
