# Generated by Django 5.2.7 on 2025-11-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_seed_homepage_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionalmessage",
            name="match_last_upload_moods",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="限定上一次上传的心情标签（任意匹配一个即满足）。",
            ),
        ),
        migrations.AddField(
            model_name="conditionalmessage",
            name="match_last_upload_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="限定上一次上传的作品标签（任意匹配一个即满足）。",
            ),
        ),
    ]
