# Generated by Django 5.2.7 on 2025-11-15 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_update_history_message_years"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="维度唯一标识，建议使用英文短标签。",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="维度名称，例如：创作风格、情绪倾向等。",
                        max_length=128,
                    ),
                ),
                (
                    "endpoint_a_code",
                    models.CharField(
                        help_text="端点A的标识（例如：o）。", max_length=16
                    ),
                ),
                (
                    "endpoint_a_name",
                    models.CharField(
                        help_text="端点A的名称（例如：有序创作）。", max_length=64
                    ),
                ),
                (
                    "endpoint_b_code",
                    models.CharField(
                        help_text="端点B的标识（例如：M）。", max_length=16
                    ),
                ),
                (
                    "endpoint_b_name",
                    models.CharField(
                        help_text="端点B的名称（例如：自由创作）。", max_length=64
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="维度描述，说明该维度评估的内容。"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="排序权重，数值越小越靠前。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "测试维度",
                "verbose_name_plural": "测试维度",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.AlterField(
            model_name="dailyhistorymessage",
            name="text",
            field=models.TextField(help_text="历史上的今天文案内容。"),
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="测试唯一标识，建议使用英文短标签。",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="测试名称，例如：创作风格评估、心境测试等。",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="测试描述，说明测试的目的和内容。"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关闭后将从用户端隐藏该测试。"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="排序权重，数值越小越靠前。"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="附加元数据，例如结果解释模板等。",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dimensions",
                    models.ManyToManyField(
                        help_text="该测试使用的维度。",
                        related_name="tests",
                        to="core.testdimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试",
                "verbose_name_plural": "测试",
                "ordering": ["display_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="题目文本，例如：你准备开始今天的绘画，却不知道先画什么："
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="题目顺序，数值越小越靠前。"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关闭后该题目将不显示。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.ForeignKey(
                        help_text="所属测试。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试题目",
                "verbose_name_plural": "测试题目",
                "ordering": ["test", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_text",
                    models.CharField(
                        help_text="选项文本，例如：会先翻之前的草稿或参考，找个入口。",
                        max_length=256,
                    ),
                ),
                (
                    "endpoint_code",
                    models.CharField(
                        help_text="该选项对应的维度端点代码（例如：o 或 M）。",
                        max_length=16,
                    ),
                ),
                (
                    "score_config",
                    models.JSONField(
                        default=dict,
                        help_text="分值配置，JSON格式。键为选择强度（-2到2），值为该选项在该强度下的得分。",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="选项顺序，数值越小越靠前。"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关闭后该选项将不显示。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="该选项对应的维度。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.testdimension",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="所属题目。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.testquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试选项",
                "verbose_name_plural": "测试选项",
                "ordering": ["question", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension_scores",
                    models.JSONField(
                        default=dict,
                        help_text="各维度端点得分，JSON格式。键为端点代码，值为得分。",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text="用户的选择记录，JSON格式。"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="完成测试的时间。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.ForeignKey(
                        help_text="完成的测试。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_results",
                        to="core.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="完成测试的用户。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户测试结果",
                "verbose_name_plural": "用户测试结果",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-completed_at"],
                        name="core_userte_user_id_f34936_idx",
                    ),
                    models.Index(
                        fields=["test", "-completed_at"],
                        name="core_userte_test_id_405138_idx",
                    ),
                ],
            },
        ),
    ]
