# Generated by Django 5.2.7 on 2025-11-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_testdimension_alter_dailyhistorymessage_text_test_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testoption",
            options={
                "ordering": ["option_text", "id"],
                "verbose_name": "测试选项",
                "verbose_name_plural": "测试选项",
            },
        ),
        migrations.RemoveField(
            model_name="testoption",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="testoption",
            name="question",
        ),
        migrations.AlterField(
            model_name="testoption",
            name="dimension",
            field=models.ForeignKey(
                help_text="该选项对应的维度。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_options",
                to="core.testdimension",
            ),
        ),
        migrations.AlterField(
            model_name="testoption",
            name="is_active",
            field=models.BooleanField(default=True, help_text="关闭后该选项将不生效。"),
        ),
        migrations.AlterField(
            model_name="testoption",
            name="score_config",
            field=models.JSONField(
                default=dict,
                help_text="分值配置，JSON格式。键为选择强度（-2到2），值为该维度端点在该强度下的得分。",
            ),
        ),
        migrations.CreateModel(
            name="TestOptionText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="选项文本，例如：会先翻之前的草稿或参考，找个入口。",
                        max_length=256,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="选项文本顺序，数值越小越靠前。"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关闭后该选项文本将不显示。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="所属题目。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_texts",
                        to="core.testquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试选项文本",
                "verbose_name_plural": "测试选项文本",
                "ordering": ["question", "display_order", "id"],
            },
        ),
        migrations.AlterField(
            model_name="testoption",
            name="option_text",
            field=models.ForeignKey(
                help_text="所属选项文本。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="core.testoptiontext",
            ),
        ),
    ]
