# Generated by Django 5.2.7 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_testoption_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="小测日期，每天只能有一个小测。", unique=True
                    ),
                ),
                ("question_text", models.TextField(help_text="题目文本。")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="排序权重，数值越小越靠前。"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关闭后该小测将不显示。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "每日小测",
                "verbose_name_plural": "每日小测",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="core_dailyq_date_efadc4_idx"),
                    models.Index(
                        fields=["is_active", "-date"],
                        name="core_dailyq_is_acti_76ffe9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyQuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("text", "文字"), ("image", "图片")],
                        default="text",
                        help_text="选项类型：文字或图片。",
                        max_length=16,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="选项文字（当选项类型为文字时使用）。",
                        max_length=256,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="选项图片（当选项类型为图片时使用）。",
                        null=True,
                        upload_to="daily_quiz/%Y/%m/",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="选项顺序，数值越小越靠前。"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关闭后该选项将不显示。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="所属每日小测。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.dailyquiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日小测选项",
                "verbose_name_plural": "每日小测选项",
                "ordering": ["quiz", "display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["quiz", "display_order"],
                        name="core_dailyq_quiz_id_acec6b_idx",
                    )
                ],
            },
        ),
    ]
