# Generated by Django 5.2.7 on 2025-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_dailyquiz_dailyquizoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="test_type",
            field=models.CharField(
                choices=[
                    (
                        "type_1",
                        "类型1：5级选择（非常同意/比较同意/中立/比较不同意/非常不同意）",
                    ),
                    ("type_2", "类型2：题目+4个选项（选择不同选项给不同维度加分）"),
                ],
                default="type_1",
                help_text="测试类型：类型1为5级选择，类型2为4个选项选择。",
                max_length=16,
            ),
        ),
    ]
