# Generated by Django 5.2.7 on 2025-11-15 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_test_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestion",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                help_text="类型1使用：该题目对应的维度。",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type1_questions",
                to="core.testdimension",
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="endpoint_code",
            field=models.CharField(
                blank=True,
                help_text="类型1使用：该题目对应的维度端点代码（例如：o 或 M）。",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="score_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="类型1使用：分值配置，JSON格式。键为选择强度（-2到2），值为该维度端点在该强度下的得分。",
            ),
        ),
    ]
