# Generated by Django 5.2.7 on 2025-11-16 22:13

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_testquestion_dimension_testquestion_endpoint_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Token过期时间，过期后需要重新登录", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dailyquizoption",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="选项图片（当选项类型为图片时使用）。",
                null=True,
                upload_to=core.models.daily_quiz_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="用户上传的作品图片。",
                null=True,
                upload_to=core.models.user_upload_path,
            ),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["expires_at"], name="core_authto_expires_713117_idx"
            ),
        ),
    ]
