# Generated by Django 5.2.7 on 2025-11-16 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_add_token_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("monthly_summary", "月度摘要"),
                            ("rhythm", "节律与习惯"),
                            ("tags", "标签快照"),
                            ("milestone_review", "节点回顾"),
                            ("creative_depth", "创作深度"),
                            ("trend_comparison", "趋势对比"),
                            ("personalized_insight", "个性化洞察"),
                        ],
                        help_text="月报部分标识。",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="模板名称，便于后台识别。", max_length=128
                    ),
                ),
                (
                    "text_template",
                    models.TextField(
                        help_text="文案模板，支持变量：{count}（上传数）、{hours}（总时长）、{avg_hours}（平均时长）、{creator_type}（创作类型）、{rating}（平均评分）、{trend}（趋势描述）等。"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="优先级，数字越小优先级越高。当多个条件同时满足时，优先显示优先级高的。",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否启用此模板。"),
                ),
                (
                    "min_total_uploads",
                    models.PositiveIntegerField(
                        blank=True, help_text="本月上传总数最低值（含）。", null=True
                    ),
                ),
                (
                    "max_total_uploads",
                    models.PositiveIntegerField(
                        blank=True, help_text="本月上传总数最高值（含）。", null=True
                    ),
                ),
                (
                    "min_total_hours",
                    models.FloatField(
                        blank=True,
                        help_text="本月总时长最低值（小时，含）。",
                        null=True,
                    ),
                ),
                (
                    "max_total_hours",
                    models.FloatField(
                        blank=True,
                        help_text="本月总时长最高值（小时，含）。",
                        null=True,
                    ),
                ),
                (
                    "min_avg_hours",
                    models.FloatField(
                        blank=True,
                        help_text="平均单张时长最低值（小时，含）。",
                        null=True,
                    ),
                ),
                (
                    "max_avg_hours",
                    models.FloatField(
                        blank=True,
                        help_text="平均单张时长最高值（小时，含）。",
                        null=True,
                    ),
                ),
                (
                    "creator_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fragmented", "碎片型创作者"),
                            ("focused", "专注型创作者"),
                            ("balanced", "平衡型创作者"),
                        ],
                        help_text="限定创作类型（碎片型、专注型、平衡型）。",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "min_avg_rating",
                    models.FloatField(
                        blank=True,
                        help_text="平均自评分最低值（含）。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "max_avg_rating",
                    models.FloatField(
                        blank=True,
                        help_text="平均自评分最高值（含）。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "uploads_change_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increase", "增加"),
                            ("decrease", "减少"),
                            ("stable", "稳定"),
                        ],
                        help_text="与上月相比上传数的变化方向。",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "hours_change_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increase", "增加"),
                            ("decrease", "减少"),
                            ("stable", "稳定"),
                        ],
                        help_text="与上月相比总时长的变化方向。",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "extra_conditions",
                    models.JSONField(
                        blank=True, default=dict, help_text="其他扩展条件（JSON格式）。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "月报文案模板",
                "verbose_name_plural": "月报文案模板",
                "ordering": ["section", "priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["section", "is_active", "priority"],
                        name="core_monthl_section_d33340_idx",
                    )
                ],
            },
        ),
    ]
