# Generated by Django 5.2.7 on 2025-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_monthlyreporttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registration_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="用户注册编号，从1开始递增。",
                null=True,
                unique=True,
            ),
        ),
    ]
