# Generated by Django 5.2.7 on 2025-11-17 14:06

from django.db import migrations, models


def assign_registration_numbers(apps, schema_editor):
    """为现有用户分配注册编号"""
    UserProfile = apps.get_model("core", "UserProfile")
    
    # 按用户创建时间排序，为每个用户分配递增的注册编号
    profiles = UserProfile.objects.filter(registration_number__isnull=True).order_by(
        "user__date_joined", "user__id"
    )
    
    # 获取当前最大注册编号
    max_number = (
        UserProfile.objects.filter(registration_number__isnull=False)
        .aggregate(max_num=models.Max("registration_number"))["max_num"]
        or 0
    )
    
    # 为每个用户分配编号
    for index, profile in enumerate(profiles, start=1):
        profile.registration_number = max_number + index
        profile.save(update_fields=["registration_number"])


def reverse_assign_registration_numbers(apps, schema_editor):
    """回滚：清除所有注册编号"""
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.all().update(registration_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_add_registration_number"),
    ]

    operations = [
        migrations.RunPython(
            assign_registration_numbers,
            reverse_assign_registration_numbers,
        ),
    ]
