# Generated by Django 5.2.7 on 2025-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_assign_registration_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="通知标题。", max_length=256)),
                (
                    "summary",
                    models.CharField(
                        help_text="通知摘要，显示在通知列表中。", max_length=512
                    ),
                ),
                ("content", models.TextField(help_text="通知正文，显示在通知详情页。")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否启用此通知。"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "系统通知",
                "verbose_name_plural": "系统通知",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_notifi_created_f19d5e_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="core_notifi_is_acti_2669a5_idx",
                    ),
                ],
            },
        ),
    ]
