# Generated by Django 5.2.7 on 2025-11-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighFiveCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="点击总数"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "击掌计数器",
                "verbose_name_plural": "击掌计数器",
            },
        ),
    ]
