# Generated by Django 5.2.7 on 2025-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_fix_dailycheckin_auto_increment"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="dimension_question_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="维度题目映射，JSON格式。键为维度ID（字符串），值为该维度对应的题目ID列表。",
            ),
        ),
    ]
