# Generated by Django 5.2.7 on 2025-11-19 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_add_dimension_question_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortTermGoalTaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="任务ID，对应schedule中的taskId。", max_length=64
                    ),
                ),
                ("date", models.DateField(help_text="完成日期，对应打卡日期。")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        help_text="关联的短期目标。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to="core.shorttermgoal",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        help_text="用户为该任务选择的上传作品。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to="core.userupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "task_id"],
                "indexes": [
                    models.Index(
                        fields=["goal", "date"], name="core_shortt_goal_id_36e5e0_idx"
                    ),
                    models.Index(
                        fields=["goal", "task_id"],
                        name="core_shortt_goal_id_7ef4ba_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("goal", "task_id", "date"),
                        name="unique_task_completion_per_goal_task_date",
                    )
                ],
            },
        ),
    ]
