# Generated by Django 5.2.7 on 2025-11-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_add_short_term_goal_task_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycheckin",
            name="notes",
            field=models.TextField(
                blank=True, help_text="用户为这一天留下的备注或感想。"
            ),
        ),
    ]
