# Generated by Django 5.2.7 on 2025-11-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_add_daily_checkin_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycheckin",
            name="checked_at",
            field=models.DateTimeField(
                auto_now=True, help_text="最后打卡时间，每次打卡都会更新"
            ),
        ),
    ]
