# Generated by Django 5.2.7 on 2025-11-19 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_change_checked_at_to_auto_now"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, help_text="尝试登录的邮箱地址", max_length=254
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        db_index=True, help_text="客户端IP地址", max_length=45
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=False, help_text="登录是否成功"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "登录尝试记录",
                "verbose_name_plural": "登录尝试记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["registration_number"], name="core_userpr_registr_3e9680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["email", "-created_at"], name="core_logina_email_94fdc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="core_logina_ip_addr_749dbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["created_at"], name="core_logina_created_b369ab_idx"
            ),
        ),
    ]
