# Generated by Django 5.2.7 on 2025-11-19 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_loginattempt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="userupload",
            old_name="tags",
            new_name="tags_old",
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="标签名称，最多24个字符。", max_length=24
                    ),
                ),
                (
                    "is_preset",
                    models.BooleanField(default=False, help_text="是否为预设标签。"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="是否隐藏（用户可隐藏预设标签或自定义标签）。",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="显示顺序，数值越小越靠前。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="标签所属用户，None表示预设标签。",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="userupload",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="上传时选择的作品标签。",
                related_name="uploads",
                to="core.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["user", "-created_at"], name="core_tag_user_id_95212f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_preset", "is_hidden"], name="core_tag_is_pres_6cfbfb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="unique_user_tag_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preset", True), ("user__isnull", True)),
                fields=("name",),
                name="unique_preset_tag_name",
            ),
        ),
    ]
