# Generated by Django 5.2.7 on 2025-11-19 16:50

from django.db import migrations


# 预设标签列表（与前端保持一致）
PRESET_TAGS = [
    {"id": "sketch", "name": "速写", "defaultActive": True},
    {"id": "daily-practice", "name": "日常练习", "defaultActive": True},
    {"id": "abstract", "name": "抽象", "defaultActive": True},
    {"id": "digital", "name": "数字绘", "defaultActive": False},
    {"id": "concept", "name": "概念设计", "defaultActive": False},
    {"id": "oil", "name": "油画", "defaultActive": False},
    {"id": "watercolor", "name": "水彩", "defaultActive": False},
    {"id": "portrait", "name": "人物", "defaultActive": False},
    {"id": "landscape", "name": "风景", "defaultActive": False},
    {"id": "fanart", "name": "同人", "defaultActive": False},
    {"id": "comic", "name": "漫画", "defaultActive": False},
    {"id": "experiment", "name": "实验", "defaultActive": False},
]


def create_preset_tags(apps, schema_editor):
    """创建预设标签"""
    Tag = apps.get_model("core", "Tag")
    
    for preset in PRESET_TAGS:
        Tag.objects.get_or_create(
            name=preset["name"],
            is_preset=True,
            user=None,
            defaults={
                "display_order": 100,
                "is_hidden": False,
            }
        )


def migrate_tags_to_relations(apps, schema_editor):
    """将旧版字符串标签转换为关联关系"""
    Tag = apps.get_model("core", "Tag")
    UserUpload = apps.get_model("core", "UserUpload")
    
    # 创建预设标签映射（名称 -> Tag对象）
    preset_tag_map = {}
    for tag in Tag.objects.filter(is_preset=True, user__isnull=True):
        preset_tag_map[tag.name] = tag
    
    # 处理所有上传记录
    uploads = UserUpload.objects.filter(tags_old__isnull=False).exclude(tags_old=[])
    total = uploads.count()
    processed = 0
    
    for upload in uploads:
        if not upload.tags_old or not isinstance(upload.tags_old, list):
            continue
        
        tag_objects = []
        for tag_name in upload.tags_old:
            if not isinstance(tag_name, str) or not tag_name.strip():
                continue
            
            tag_name = tag_name.strip()
            
            # 先检查是否是预设标签
            if tag_name in preset_tag_map:
                tag_objects.append(preset_tag_map[tag_name])
            else:
                # 创建或获取用户自定义标签
                custom_tag, created = Tag.objects.get_or_create(
                    name=tag_name,
                    user=upload.user,
                    is_preset=False,
                    defaults={
                        "display_order": 100,
                        "is_hidden": False,
                    }
                )
                tag_objects.append(custom_tag)
        
        # 建立关联关系
        if tag_objects:
            upload.tags.set(tag_objects)
        
        processed += 1
        if processed % 100 == 0:
            print(f"已处理 {processed}/{total} 条记录...")


def reverse_migration(apps, schema_editor):
    """反向迁移：将关联关系转换回字符串数组（仅用于回滚）"""
    Tag = apps.get_model("core", "Tag")
    UserUpload = apps.get_model("core", "UserUpload")
    
    for upload in UserUpload.objects.all():
        tag_names = list(upload.tags.values_list("name", flat=True))
        upload.tags_old = tag_names
        upload.save(update_fields=["tags_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_add_tag_model"),
    ]

    operations = [
        migrations.RunPython(create_preset_tags, migrations.RunPython.noop),
        migrations.RunPython(migrate_tags_to_relations, reverse_migration),
    ]
