# Generated by Django 5.2.7 on 2025-11-20 20:15

import config.storage
import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_migrate_tags_to_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyreporttemplate",
            name="max_avg_rating",
            field=models.FloatField(
                blank=True,
                help_text="平均自评分最高值（含），范围 0-100。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreporttemplate",
            name="min_avg_rating",
            field=models.FloatField(
                blank=True,
                help_text="平均自评分最低值（含），范围 0-100。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="用户上传的作品图片。",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.user_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="mood_label",
            field=models.CharField(
                blank=True,
                help_text="[已废弃] 旧版状态存储，仅用于数据迁移。",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="tags_old",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[已废弃] 旧版标签存储，仅用于数据迁移。",
            ),
        ),
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="状态名称，如'灵感爆棚'、'画感全开'等。",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="显示顺序，数值越小越靠前。"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否启用该状态。"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="core_mood_is_acti_c43085_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="userupload",
            name="mood",
            field=models.ForeignKey(
                blank=True,
                help_text="上传时选择的创作状态。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploads",
                to="core.mood",
            ),
        ),
    ]
