# Generated by Django 5.2.7 on 2025-11-20 20:15

from django.db import migrations


def seed_mood_data(apps, schema_editor):
    """创建预设的16种创作状态"""
    Mood = apps.get_model("core", "Mood")
    
    moods = [
        {"name": "灵感爆棚", "display_order": 1},
        {"name": "画感全开", "display_order": 2},
        {"name": "稳扎慢练", "display_order": 3},
        {"name": "卡住反复", "display_order": 4},
        {"name": "惊喜超标", "display_order": 5},
        {"name": "随便摸鱼", "display_order": 6},
        {"name": "换法试笔", "display_order": 7},
        {"name": "小小进步", "display_order": 8},
        {"name": "爆肝冲刺", "display_order": 9},
        {"name": "疲惫挂机", "display_order": 10},
        {"name": "细节打磨", "display_order": 11},
        {"name": "产能见底", "display_order": 12},
        {"name": "画废崩溃", "display_order": 13},
        {"name": "自我怀疑", "display_order": 14},
        {"name": "摆烂自救", "display_order": 15},
        {"name": "情绪重启", "display_order": 16},
    ]
    
    for mood_data in moods:
        Mood.objects.get_or_create(
            name=mood_data["name"],
            defaults={
                "display_order": mood_data["display_order"],
                "is_active": True,
            }
        )


def reverse_seed_mood_data(apps, schema_editor):
    """删除预设的创作状态"""
    Mood = apps.get_model("core", "Mood")
    Mood.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_add_mood_model"),
    ]

    operations = [
        migrations.RunPython(seed_mood_data, reverse_seed_mood_data),
    ]
