# Generated by Django 5.2.7 on 2025-11-20 20:16

from django.db import migrations


def migrate_mood_label_to_mood(apps, schema_editor):
    """将现有的mood_label字符串转换为Mood对象"""
    UserUpload = apps.get_model("core", "UserUpload")
    Mood = apps.get_model("core", "Mood")
    
    # 获取所有有mood_label的上传记录
    uploads = UserUpload.objects.filter(mood_label__isnull=False).exclude(mood_label="")
    
    migrated_count = 0
    skipped_count = 0
    
    for upload in uploads:
        mood_label = upload.mood_label.strip()
        if not mood_label:
            continue
        
        # 查找对应的Mood对象
        try:
            mood = Mood.objects.get(name=mood_label)
            upload.mood = mood
            upload.save(update_fields=["mood"])
            migrated_count += 1
        except Mood.DoesNotExist:
            # 如果找不到对应的Mood，跳过（保留mood_label用于后续处理）
            skipped_count += 1
            print(f"Warning: Mood '{mood_label}' not found for upload {upload.id}")
    
    print(f"Migrated {migrated_count} uploads, skipped {skipped_count} uploads")


def reverse_migrate_mood_label_to_mood(apps, schema_editor):
    """将Mood对象转换回mood_label字符串"""
    UserUpload = apps.get_model("core", "UserUpload")
    
    uploads = UserUpload.objects.filter(mood__isnull=False)
    
    for upload in uploads:
        if upload.mood:
            upload.mood_label = upload.mood.name
            upload.save(update_fields=["mood_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_seed_mood_data"),
    ]

    operations = [
        migrations.RunPython(migrate_mood_label_to_mood, reverse_migrate_mood_label_to_mood),
    ]
