# Generated by Django 5.2.7 on 2025-11-21 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_migrate_mood_label_to_mood"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="collection_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="套图ID，相同ID的作品属于同一个套图。",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userupload",
            name="collection_index",
            field=models.PositiveIntegerField(
                blank=True, help_text="在套图中的序号，从1开始。", null=True
            ),
        ),
        migrations.AddField(
            model_name="userupload",
            name="collection_name",
            field=models.CharField(
                blank=True,
                help_text="套图名称，同一套图内的作品共享相同的名称。",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="userupload",
            index=models.Index(
                fields=["collection_id", "collection_index"],
                name="core_userup_collect_9e3624_idx",
            ),
        ),
    ]
