# Generated by Django 5.2.7 on 2025-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_add_collection_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="longtermgoal",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="附加元数据，用于存储checkpoint的自定义数据（showcase和completionNote）。",
            ),
        ),
    ]
