# Generated by Django 5.2.7 on 2025-11-21 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_longtermgoal_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.PositiveIntegerField(
                default=150, help_text="用户点数余额，默认150点。"
            ),
        ),
        migrations.CreateModel(
            name="PointsOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="订单号，唯一标识。",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("points", models.PositiveIntegerField(help_text="充值点数。")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="订单金额（元）。", max_digits=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("wechat", "微信支付"), ("alipay", "支付宝")],
                        help_text="支付方式。",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("failed", "支付失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        help_text="订单状态。",
                        max_length=16,
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="第三方支付交易号。",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="支付完成时间。", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="下单用户。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "点数充值订单",
                "verbose_name_plural": "点数充值订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("recharge", "充值"),
                            ("consume", "消费"),
                            ("refund", "退款"),
                        ],
                        help_text="交易类型。",
                        max_length=16,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="变动点数（正数为增加，负数为减少）。"
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(help_text="交易后余额。"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="交易描述。", max_length=256
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="关联的订单（如果是充值交易）。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.pointsorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="交易用户。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "点数交易记录",
                "verbose_name_plural": "点数交易记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pointsorder",
            index=models.Index(
                fields=["user", "-created_at"], name="core_points_user_id_2dc31e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointsorder",
            index=models.Index(
                fields=["order_number"], name="core_points_order_n_31825f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointsorder",
            index=models.Index(
                fields=["status", "-created_at"], name="core_points_status_a9d749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointstransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="core_points_user_id_a1f873_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointstransaction",
            index=models.Index(
                fields=["transaction_type", "-created_at"],
                name="core_points_transac_cd0e1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointstransaction",
            index=models.Index(fields=["order"], name="core_points_order_i_70c542_idx"),
        ),
    ]
