# Generated by Django 5.2.7 on 2025-11-21 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_add_points_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shorttermgoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "暂存"),
                    ("saved", "已保存未进行"),
                    ("active", "进行中"),
                    ("completed", "已完成"),
                ],
                default="draft",
                help_text="目标状态：暂存、已保存未进行、进行中、已完成。",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="shorttermgoal",
            index=models.Index(
                fields=["user", "status"], name="core_shortt_user_id_fc995e_idx"
            ),
        ),
    ]
