# Generated by Django 5.2.7 on 2025-11-21 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_add_short_term_goal_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(help_text="年份")),
                ("month", models.PositiveIntegerField(help_text="月份（1-12）")),
                (
                    "total_uploads",
                    models.PositiveIntegerField(default=0, help_text="总上传数"),
                ),
                (
                    "total_hours",
                    models.FloatField(default=0.0, help_text="总时长（小时）"),
                ),
                (
                    "avg_hours_per_upload",
                    models.FloatField(default=0.0, help_text="平均单张时长（小时）"),
                ),
                ("avg_rating", models.FloatField(default=0.0, help_text="平均自评分")),
                (
                    "most_upload_day_date",
                    models.DateField(blank=True, help_text="最多上传日期", null=True),
                ),
                (
                    "most_upload_day_count",
                    models.PositiveIntegerField(
                        default=0, help_text="最多上传日期数量"
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="当前连续打卡天数"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="最长连续打卡天数"
                    ),
                ),
                (
                    "time_distribution",
                    models.JSONField(
                        default=list,
                        help_text="时段分布，格式：[{hour: 0-23, count: number, percentage: number}, ...]",
                    ),
                ),
                (
                    "weekly_distribution",
                    models.JSONField(
                        default=list,
                        help_text="周内分布，格式：[{weekday: 0-6, count: number, minutes: number}, ...]",
                    ),
                ),
                (
                    "tag_stats",
                    models.JSONField(
                        default=list,
                        help_text="标签统计，格式：[{tag: string, count: number, percentage: number, avgDurationMinutes: number, avgRating: number}, ...]",
                    ),
                ),
                (
                    "heatmap_calendar",
                    models.JSONField(
                        default=list,
                        help_text="日历热力图，格式：[{day: 1-31, count: number, weekday: 0-6, opacity: 0-1}, ...]",
                    ),
                ),
                (
                    "upload_ids",
                    models.JSONField(default=list, help_text="本月上传记录ID列表"),
                ),
                (
                    "report_texts",
                    models.JSONField(
                        default=dict,
                        help_text="月报文案，格式：{section: rendered_text, ...}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "固定月报",
                "verbose_name_plural": "固定月报",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["user", "-year", "-month"],
                        name="core_monthl_user_id_5ab5c5_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="core_monthl_year_9d57f3_idx"
                    ),
                ],
                "unique_together": {("user", "year", "month")},
            },
        ),
    ]
