# Generated by Django 5.2.7 on 2025-11-21 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_add_monthly_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="成就解锁时间（首次满足条件的时间）。",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        help_text="被解锁的成就。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="core.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="解锁成就的用户。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户成就解锁记录",
                "verbose_name_plural": "用户成就解锁记录",
                "ordering": ["-unlocked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "achievement"],
                        name="core_userac_user_id_82a945_idx",
                    ),
                    models.Index(
                        fields=["user", "-unlocked_at"],
                        name="core_userac_user_id_fbd34d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "achievement"),
                        name="core_userachievement_unique_user_achievement",
                    )
                ],
            },
        ),
    ]
