# Generated by Django 5.2.7 on 2025-11-21 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_add_user_achievement_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievement",
            name="unlocked_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="成就解锁时间（首次满足条件的时间）。",
            ),
        ),
    ]
