# Generated by Django 5.2.7 on 2025-11-21 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_update_user_achievement_unlocked_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        db_index=True,
                        help_text="指标名称，如 total_uploads, current_streak 等。",
                        max_length=64,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        help_text="操作符：>=, >, <=, <, ==, !=。", max_length=8
                    ),
                ),
                ("threshold", models.FloatField(help_text="阈值。")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="显示顺序，用于多条件组合。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "成就条件子项",
                "verbose_name_plural": "成就条件子项",
                "ordering": ["achievement", "display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="userachievement",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="解锁时的元数据快照，例如触发的指标值、条件详情等。",
            ),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("auto", "自动解锁"),
                    ("manual", "手动解锁"),
                    ("inferred", "历史推断"),
                    ("legacy", "历史数据"),
                ],
                default="legacy",  # 现有记录默认为 legacy
                help_text="解锁来源：自动/手动/推断/历史。",
                max_length=32,
            ),
        ),
        # 数据迁移：为现有记录设置 provenance 为 legacy
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("core", "UserAchievement").objects.all().update(provenance="legacy"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["provenance"], name="core_userac_provena_681bcb_idx"
            ),
        ),
        migrations.AddField(
            model_name="achievementcondition",
            name="achievement",
            field=models.ForeignKey(
                help_text="关联的成就。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_items",
                to="core.achievement",
            ),
        ),
        migrations.AddIndex(
            model_name="achievementcondition",
            index=models.Index(
                fields=["achievement", "metric"], name="core_achiev_achieve_037ab6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievementcondition",
            index=models.Index(
                fields=["metric", "operator", "threshold"],
                name="core_achiev_metric_2fd6da_idx",
            ),
        ),
    ]
