# Generated by Django 5.2.7 on 2025-11-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_add_achievement_provenance_and_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievement",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("auto", "自动解锁"),
                    ("manual", "手动解锁"),
                    ("inferred", "历史推断"),
                    ("legacy", "历史数据"),
                ],
                default="auto",
                help_text="解锁来源：自动/手动/推断/历史。",
                max_length=32,
            ),
        ),
    ]
