# Generated by Django 5.2.7 on 2025-11-21 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_add_monthly_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_uploads",
                    models.PositiveIntegerField(default=0, help_text="总上传数"),
                ),
                (
                    "total_checkins",
                    models.PositiveIntegerField(default=0, help_text="总打卡次数"),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="当前连续打卡天数"
                    ),
                ),
                (
                    "checked_today",
                    models.BooleanField(default=False, help_text="今天是否打卡"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, help_text="最后更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户统计",
                "verbose_name_plural": "用户统计",
                "indexes": [
                    models.Index(
                        fields=["last_updated"], name="core_userst_last_up_833bc2_idx"
                    )
                ],
            },
        ),
    ]
