# Generated by Django 5.2.7 on 2025-11-24 18:35

import config.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_add_user_stats_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="作品缩略图，用于列表页展示，节省CDN流量。",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.user_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="shorttermgoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("saved", "已保存未进行"),
                    ("active", "进行中"),
                    ("completed", "已完成"),
                ],
                default="saved",
                help_text="目标状态：已保存未进行、进行中、已完成。",
                max_length=16,
            ),
        ),
    ]
