# Generated by Django 5.2.7 on 2025-11-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_add_thumbnail_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.TextField(help_text="原始图片（base64编码）"),
                ),
                ("step1_binary", models.TextField(help_text="第一步：二值化结果")),
                ("step2_grayscale", models.TextField(help_text="第二步：RGB转灰度")),
                ("step3_lab_l", models.TextField(help_text="第三步：LAB的L通道")),
                ("step4_hsv_s", models.TextField(help_text="第四步：HSV饱和度")),
                ("step4_hls_s", models.TextField(help_text="第四步：HLS饱和度")),
                ("step5_hue", models.TextField(help_text="第五步：纯色相图")),
                (
                    "binary_threshold",
                    models.IntegerField(
                        default=128, help_text="二值化阈值（-1表示Otsu自动）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_analysis_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "视觉分析结果",
                "verbose_name_plural": "视觉分析结果",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_visual_user_id_17e9c5_idx",
                    )
                ],
            },
        ),
    ]
