# Generated by Django 5.2.7 on 2025-11-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_visualanalysisresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualanalysisresult",
            name="comprehensive_analysis",
            field=models.JSONField(
                blank=True, default=dict, help_text="专业绘画分析结果（JSON格式）"
            ),
        ),
    ]
