# Generated by Django 5.2.7 on 2025-11-25 23:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_visualanalysisresult_comprehensive_analysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Celery 任务ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("started", "处理中"),
                            ("success", "成功"),
                            ("failure", "失败"),
                            ("retry", "重试中"),
                            ("revoked", "已取消"),
                        ],
                        default="pending",
                        help_text="任务状态",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        help_text="进度百分比（0-100）",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="错误信息（如果失败）", null=True
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="分析结果数据"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_analysis_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "图像分析任务",
                "verbose_name_plural": "图像分析任务",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_imagea_user_id_32823b_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="core_imagea_task_id_582a1b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_imagea_status_f440dc_idx"
                    ),
                ],
            },
        ),
    ]
