# Generated by Django 5.2.7 on 2025-11-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_imageanalysistask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step4_hsv_s",
            field=models.TextField(
                blank=True, default="", help_text="第四步：HSV饱和度"
            ),
        ),
    ]
