# Generated by Django 5.2.7 on 2025-11-26 17:02

import config.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_make_step4_hsv_s_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="original_image",
            field=models.ImageField(
                help_text="原始图片",
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_original_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step1_binary",
            field=models.ImageField(
                help_text="第一步：二值化结果",
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step1_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step2_grayscale",
            field=models.ImageField(
                help_text="第二步：RGB转灰度",
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step2_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step3_lab_l",
            field=models.ImageField(
                help_text="第三步：LAB的L通道",
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step3_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step4_hls_s",
            field=models.ImageField(
                help_text="第四步：HLS饱和度",
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step4_hls_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step4_hsv_s",
            field=models.ImageField(
                blank=True,
                help_text="第四步：HSV饱和度",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step4_hsv_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step5_hue",
            field=models.ImageField(
                help_text="第五步：纯色相图",
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step5_upload_path,
            ),
        ),
    ]
