# Generated by Django 5.2.7 on 2025-11-27 14:17

import config.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_change_visual_analysis_to_imagefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualanalysisresult",
            name="kmeans_segmentation_image",
            field=models.ImageField(
                blank=True,
                help_text="K-means色块分割图",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_kmeans_segmentation_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="visualanalysisresult",
            name="step2_grayscale_3_level",
            field=models.ImageField(
                blank=True,
                help_text="3阶层灰度图",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step2_grayscale_3_level_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="visualanalysisresult",
            name="step2_grayscale_4_level",
            field=models.ImageField(
                blank=True,
                help_text="4阶层灰度图",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step2_grayscale_4_level_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="visualanalysisresult",
            name="step4_hls_s_inverted",
            field=models.ImageField(
                blank=True,
                help_text="HLS饱和度反色图",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step4_hls_s_inverted_upload_path,
            ),
        ),
    ]
