# Generated by Django 5.2.7 on 2025-11-27 17:19

import config.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_add_visual_analysis_extra_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="step2_grayscale",
            field=models.ImageField(
                blank=True,
                help_text="第二步：RGB转灰度（已废弃，新流程使用step2_grayscale_3_level和step2_grayscale_4_level）",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_step2_upload_path,
            ),
        ),
    ]
