# Generated by Django 5.2.7 on 2025-11-27 20:58

import config.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_make_step2_grayscale_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualanalysisresult",
            name="kmeans_segmentation_image_12",
            field=models.ImageField(
                blank=True,
                help_text="K-means色块分割图（Step5，12色）",
                null=True,
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_kmeans_segmentation_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisresult",
            name="kmeans_segmentation_image",
            field=models.ImageField(
                help_text="K-means色块分割图（Step5，8色）",
                storage=config.storage.TOSMediaStorage(),
                upload_to=core.models.visual_analysis_kmeans_segmentation_upload_path,
            ),
        ),
    ]
