# Generated by Django 5.2.7 on 2025-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_add_kmeans_segmentation_image_12"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="ip_address",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="客户端IP地址，用于IP级别限流（从metadata中提取）",
                max_length=45,
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="core_emailv_ip_addr_0f5f72_idx",
            ),
        ),
    ]
