# Generated by Django 5.2.7 on 2025-11-29 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_populate_ip_address_from_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="longtermgoal",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="是否已归档（用于保留历史完成记录，而不是物理删除）。",
            ),
        ),
        migrations.AddIndex(
            model_name="longtermgoal",
            index=models.Index(
                fields=["user", "is_archived", "-created_at"],
                name="core_lt_goal_user_archived_idx",
            ),
        ),
    ]
