# Generated by Django 5.2.7 on 2025-12-04 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_remove_registration_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="后台展示用昵称，默认为邮箱前缀。",
                        max_length=128,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="测试账号备注，例如用途、测试场景等。"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="自定义标签列表，便于分类筛选。",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="附加元数据，例如模拟配置。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["user__email"],
            },
        ),
        migrations.RemoveIndex(
            model_name="userupload",
            name="core_userup_collect_9e3624_idx",
        ),
        migrations.RenameIndex(
            model_name="usertaskpreset",
            new_name="core_userta_user_id_8e1699_idx",
            old_name="core_usert_user_id_a5e152_idx",
        ),
        migrations.RenameIndex(
            model_name="usertaskpreset",
            new_name="core_userta_user_id_a30a0f_idx",
            old_name="core_usert_user_id_8036e5_idx",
        ),
        migrations.RemoveField(
            model_name="userupload",
            name="collection_id",
        ),
        migrations.RemoveField(
            model_name="userupload",
            name="collection_index",
        ),
        migrations.RemoveField(
            model_name="userupload",
            name="collection_name",
        ),
        migrations.AddField(
            model_name="testaccountprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
