# Generated by Django 5.2.7 on 2025-12-04 12:46

from django.db import migrations


# 默认标签列表（用户可自由增减）
DEFAULT_TAGS = [
    {"name": "速写", "display_order": 1},
    {"name": "练习", "display_order": 2},
    {"name": "草稿", "display_order": 3},
    {"name": "成图", "display_order": 4},
    {"name": "稿件", "display_order": 5},
    {"name": "临摹", "display_order": 6},
    {"name": "设定", "display_order": 7},
]


def initialize_default_tags(apps, schema_editor):
    """为所有用户初始化默认标签"""
    Tag = apps.get_model("core", "Tag")
    User = apps.get_model("auth", "User")
    
    # 获取所有用户
    users = User.objects.all()
    total_users = users.count()
    processed = 0
    
    for user in users:
        # 为每个用户创建默认标签（如果不存在）
        for tag_data in DEFAULT_TAGS:
            Tag.objects.get_or_create(
                user=user,
                name=tag_data["name"],
                defaults={
                    "is_preset": False,
                    "is_hidden": False,
                    "display_order": tag_data["display_order"],
                }
            )
        
        processed += 1
        if processed % 100 == 0:
            print(f"已处理 {processed}/{total_users} 个用户...")


def reverse_initialize_default_tags(apps, schema_editor):
    """反向迁移：删除默认标签（可选，谨慎使用）"""
    Tag = apps.get_model("core", "Tag")
    
    # 删除所有默认标签（仅当标签名称匹配且没有画作使用时）
    default_tag_names = [tag["name"] for tag in DEFAULT_TAGS]
    
    for tag in Tag.objects.filter(name__in=default_tag_names):
        # 检查是否有画作使用此标签
        if tag.uploads.count() == 0:
            tag.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_remove_collection_fields"),
    ]

    operations = [
        migrations.RunPython(initialize_default_tags, reverse_initialize_default_tags),
    ]
