# Generated by Django 5.2.7 on 2025-12-05 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_initialize_default_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualAnalysisQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_quota",
                    models.PositiveIntegerField(
                        default=10, help_text="赠送的免费额度（新用户一次性10次）"
                    ),
                ),
                (
                    "monthly_quota",
                    models.PositiveIntegerField(
                        default=0, help_text="会员月度额度（每月60次）"
                    ),
                ),
                (
                    "current_month",
                    models.CharField(
                        blank=True,
                        help_text="当前月份（格式：YYYY-MM），用于判断是否需要重置月度额度",
                        max_length=7,
                    ),
                ),
                (
                    "used_free_quota",
                    models.PositiveIntegerField(
                        default=0, help_text="已使用的免费额度"
                    ),
                ),
                (
                    "used_monthly_quota",
                    models.PositiveIntegerField(
                        default=0, help_text="本月已使用的月度额度"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_analysis_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "视觉分析额度",
                "verbose_name_plural": "视觉分析额度",
            },
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_member",
            field=models.BooleanField(default=False, help_text="是否为EchoDraw会员。"),
        ),
        migrations.AddIndex(
            model_name="visualanalysisquota",
            index=models.Index(fields=["user"], name="core_visual_user_id_07e9af_idx"),
        ),
        migrations.AddIndex(
            model_name="visualanalysisquota",
            index=models.Index(
                fields=["current_month"], name="core_visual_current_7c4742_idx"
            ),
        ),
    ]
