# Generated by Django 5.2.7 on 2025-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_add_membership_and_visual_analysis_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="membership_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="会员到期时间。如果为None，表示非会员或永久会员。",
                null=True,
            ),
        ),
    ]
