# Generated by Django 5.2.7 on 2025-12-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_add_membership_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="featured_artwork_ids",
            field=models.JSONField(
                blank=True, default=list, help_text="用户选择在个人页展示的作品ID列表。"
            ),
        ),
    ]
