# Generated by Django 5.2.7 on 2025-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_fix_emailverification_auto_increment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorttermgoal",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="目标启动时间，当状态从saved变为active时记录。",
                null=True,
            ),
        ),
    ]
