# Generated by Django 5.2.7 on 2025-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_add_started_at_to_short_term_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointsorder",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="附加元数据，用于存储会员信息等。"
            ),
        ),
    ]
