# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations


# 新的预设标签列表（与前端保持一致）
NEW_PRESET_TAGS = [
    {"id": "sketch", "name": "速写", "display_order": 1},
    {"id": "draft", "name": "草稿", "display_order": 2},
    {"id": "final", "name": "成图", "display_order": 3},
    {"id": "copy", "name": "临摹", "display_order": 4},
    {"id": "oc", "name": "oc", "display_order": 5},
    {"id": "practice", "name": "练习", "display_order": 6},
]

# 旧的预设标签名称（需要删除的）
OLD_PRESET_TAG_NAMES = [
    "日常练习",
    "抽象",
    "数字绘",
    "概念设计",
    "油画",
    "水彩",
    "人物",
    "风景",
    "同人",
    "漫画",
    "实验",
]


def replace_preset_tags(apps, schema_editor):
    """删除旧的预设标签，创建新的预设标签"""
    Tag = apps.get_model("core", "Tag")
    UserUpload = apps.get_model("core", "UserUpload")
    
    # 删除旧的预设标签（除了"速写"，因为它在新列表中）
    old_tags = Tag.objects.filter(
        is_preset=True,
        user__isnull=True,
        name__in=OLD_PRESET_TAG_NAMES
    )
    
    # 检查这些标签是否被使用
    for old_tag in old_tags:
        # 如果标签被使用，先移除关联关系
        uploads_using_tag = UserUpload.objects.filter(tags=old_tag)
        if uploads_using_tag.exists():
            print(f"警告：预设标签 '{old_tag.name}' 被 {uploads_using_tag.count()} 个作品使用，将移除关联关系")
            for upload in uploads_using_tag:
                upload.tags.remove(old_tag)
        
        # 删除标签
        old_tag.delete()
        print(f"已删除旧预设标签: {old_tag.name}")
    
    # 创建新的预设标签（如果不存在）
    for preset in NEW_PRESET_TAGS:
        tag, created = Tag.objects.get_or_create(
            name=preset["name"],
            is_preset=True,
            user=None,
            defaults={
                "display_order": preset["display_order"],
                "is_hidden": False,
            }
        )
        if created:
            print(f"已创建新预设标签: {preset['name']}")
        else:
            # 如果已存在，更新 display_order
            tag.display_order = preset["display_order"]
            tag.is_hidden = False
            tag.save(update_fields=["display_order", "is_hidden"])
            print(f"已更新预设标签: {preset['name']}")


def reverse_replace_preset_tags(apps, schema_editor):
    """反向迁移：恢复旧的预设标签（仅用于回滚）"""
    Tag = apps.get_model("core", "Tag")
    
    # 删除新的预设标签（除了"速写"）
    new_tag_names = [tag["name"] for tag in NEW_PRESET_TAGS if tag["name"] != "速写"]
    Tag.objects.filter(
        is_preset=True,
        user__isnull=True,
        name__in=new_tag_names
    ).delete()
    
    # 恢复旧的预设标签
    OLD_PRESET_TAGS = [
        {"name": "日常练习", "display_order": 2},
        {"name": "抽象", "display_order": 3},
        {"name": "数字绘", "display_order": 4},
        {"name": "概念设计", "display_order": 5},
        {"name": "油画", "display_order": 6},
        {"name": "水彩", "display_order": 7},
        {"name": "人物", "display_order": 8},
        {"name": "风景", "display_order": 9},
        {"name": "同人", "display_order": 10},
        {"name": "漫画", "display_order": 11},
        {"name": "实验", "display_order": 12},
    ]
    
    for preset in OLD_PRESET_TAGS:
        Tag.objects.get_or_create(
            name=preset["name"],
            is_preset=True,
            user=None,
            defaults={
                "display_order": preset["display_order"],
                "is_hidden": False,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_fix_userupload_shorttermgoal_auto_increment"),
    ]

    operations = [
        migrations.RunPython(replace_preset_tags, reverse_replace_preset_tags),
    ]

