# Generated by Django 5.2.7 on 2025-12-12 23:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def safe_remove_highfive_models(apps, schema_editor):
    """安全地删除HighFive相关模型（如果存在）"""
    from django.db import connection
    
    # 检查表是否存在并删除
    with connection.cursor() as cursor:
        db_vendor = connection.vendor
        
        # 检查并删除HighFiveClick表
        table_exists = False
        if db_vendor == 'mysql':
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = DATABASE() 
                AND table_name = 'core_highfiveclick'
            """)
            table_exists = cursor.fetchone()[0] > 0
        elif db_vendor == 'sqlite':
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='table' AND name='core_highfiveclick'
            """)
            table_exists = cursor.fetchone() is not None
        
        if table_exists:
            cursor.execute("DROP TABLE IF EXISTS core_highfiveclick")
        
        # 检查并删除HighFiveCounter表
        table_exists = False
        if db_vendor == 'mysql':
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = DATABASE() 
                AND table_name = 'core_highfivecounter'
            """)
            table_exists = cursor.fetchone()[0] > 0
        elif db_vendor == 'sqlite':
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='table' AND name='core_highfivecounter'
            """)
            table_exists = cursor.fetchone() is not None
        
        if table_exists:
            cursor.execute("DROP TABLE IF EXISTS core_highfivecounter")


def safe_remove_highfive_models_reverse(apps, schema_editor):
    """反向操作：不需要实现"""
    pass


def safe_remove_kmeans_field(apps, schema_editor):
    """安全地删除kmeans_segmentation_image_12字段（如果存在）"""
    from django.db import connection
    
    # 检查字段是否存在并删除
    with connection.cursor() as cursor:
        db_vendor = connection.vendor
        
        field_exists = False
        if db_vendor == 'mysql':
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE() 
                AND table_name = 'core_visualanalysisresult'
                AND column_name = 'kmeans_segmentation_image_12'
            """)
            field_exists = cursor.fetchone()[0] > 0
        elif db_vendor == 'sqlite':
            # SQLite 不支持直接检查列是否存在，尝试删除（如果不存在会失败，但我们可以捕获异常）
            try:
                cursor.execute("PRAGMA table_info(core_visualanalysisresult)")
                columns = [row[1] for row in cursor.fetchall()]
                field_exists = 'kmeans_segmentation_image_12' in columns
            except Exception:
                field_exists = False
        
        if field_exists:
            if db_vendor == 'mysql':
                cursor.execute("ALTER TABLE core_visualanalysisresult DROP COLUMN kmeans_segmentation_image_12")
            elif db_vendor == 'sqlite':
                # SQLite 不支持 DROP COLUMN，需要重建表（这里简化处理，如果字段不存在就跳过）
                try:
                    # SQLite 的 DROP COLUMN 需要 SQLite 3.35.0+，如果版本不够，这里会失败
                    # 但通常这个字段可能不存在，所以可以安全跳过
                    pass
                except Exception:
                    pass


def safe_remove_kmeans_field_reverse(apps, schema_editor):
    """反向操作：不需要实现"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_replace_preset_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 使用RunPython安全删除可能不存在的模型和字段（数据库操作）
        migrations.RunPython(
            safe_remove_highfive_models,
            safe_remove_highfive_models_reverse,
        ),
        migrations.RunPython(
            safe_remove_kmeans_field,
            safe_remove_kmeans_field_reverse,
        ),
        # 注意：我们不使用SeparateDatabaseAndState来更新迁移状态
        # 因为如果模型在迁移状态中不存在，会导致KeyError
        # 数据库操作已经完成，迁移状态会在后续操作中自动更新
        migrations.AddField(
            model_name="longtermgoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("10000-hours", "一万小时定律"),
                    ("3-months", "3个月学习法"),
                    ("yearly", "全年计划"),
                ],
                default="10000-hours",
                help_text="长期目标类型。",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="longtermgoal",
            name="target_rounds",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="目标轮数（仅用于3-months类型）。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="checkpoint_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="检查点数量，用于划分阶段（仅用于10000-hours类型）。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="附加元数据，用于存储checkpoint的自定义数据（showcase和completionNote）或rounds数据（3个月学习法）。",
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="target_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="目标投入总小时数（仅用于10000-hours类型）。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="long_term_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="current_month",
            field=models.CharField(
                blank=True,
                help_text="当前日期标识（格式：YYYY-MM-DD），用于判断是否需要重置每日额度",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="free_quota",
            field=models.PositiveIntegerField(
                default=5, help_text="赠送的免费额度（新用户一次性5次）"
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="monthly_quota",
            field=models.PositiveIntegerField(
                default=0, help_text="会员每日额度（每天15次，每天0点刷新）"
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="used_monthly_quota",
            field=models.PositiveIntegerField(
                default=0, help_text="今日已使用的每日额度"
            ),
        ),
    ]
