# Generated by Django 5.2.7 on 2025-12-12 23:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_replace_preset_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="highfiveclick",
            name="user",
        ),
        migrations.DeleteModel(
            name="HighFiveCounter",
        ),
        migrations.RemoveField(
            model_name="visualanalysisresult",
            name="kmeans_segmentation_image_12",
        ),
        migrations.AddField(
            model_name="longtermgoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("10000-hours", "一万小时定律"),
                    ("3-months", "3个月学习法"),
                    ("yearly", "全年计划"),
                ],
                default="10000-hours",
                help_text="长期目标类型。",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="longtermgoal",
            name="target_rounds",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="目标轮数（仅用于3-months类型）。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="checkpoint_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="检查点数量，用于划分阶段（仅用于10000-hours类型）。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="附加元数据，用于存储checkpoint的自定义数据（showcase和completionNote）或rounds数据（3个月学习法）。",
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="target_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="目标投入总小时数（仅用于10000-hours类型）。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="long_term_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="current_month",
            field=models.CharField(
                blank=True,
                help_text="当前日期标识（格式：YYYY-MM-DD），用于判断是否需要重置每日额度",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="free_quota",
            field=models.PositiveIntegerField(
                default=5, help_text="赠送的免费额度（新用户一次性5次）"
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="monthly_quota",
            field=models.PositiveIntegerField(
                default=0, help_text="会员每日额度（每天15次，每天0点刷新）"
            ),
        ),
        migrations.AlterField(
            model_name="visualanalysisquota",
            name="used_monthly_quota",
            field=models.PositiveIntegerField(
                default=0, help_text="今日已使用的每日额度"
            ),
        ),
        migrations.DeleteModel(
            name="HighFiveClick",
        ),
    ]
