# Generated by Django 5.2.7 on 2025-12-13 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_remove_highfiveclick_user_delete_highfivecounter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearlyGoalPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="预设内容文字，最多50个字符。", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否启用该预设内容。"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100, help_text="显示顺序，数值越小越靠前。"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "全年计划预设内容",
                "verbose_name_plural": "全年计划预设内容",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="longtermgoal",
            name="days_per_phase",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="每个阶段的天数，范围7-21天（仅用于yearly类型）。",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(7),
                    django.core.validators.MaxValueValidator(21),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="longtermgoal",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="附加元数据，用于存储checkpoint的自定义数据（showcase和completionNote）、rounds数据（3个月学习法）或phases数据（全年计划）。",
            ),
        ),
        migrations.AddIndex(
            model_name="yearlygoalpreset",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="core_yearly_is_acti_b7b48f_idx",
            ),
        ),
    ]
